services:
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: ../Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - $HOME/.aws:/root/.aws
