services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ../Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - $HOME/.aws:/root/.aws
