services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ../Dockerfile
    env_file: .env
    volumes:
      - ./backend:/app
      - ./frontend/public/data:/data
      - $HOME/.aws:/root/.aws
