name: "Execute Just command with AWS OIDC"
description: "Sets up Just, configures AWS OIDC authentication and runs just action"

inputs:
  just_version:
    description: "Version of Just to install"
    required: false
    default: "1.0.0"
  aws_region:
    description: "AWS Region"
    default: "eu-west-2"
  aws_oidc_role_arn:
    description: "AWS iam role arn"
    required: true
  just_action:
    description: "Just action (script) to perform"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Just
      uses: extractions/setup-just@v2
      with:
        just-version: ${{ inputs.just_version }}

    - name: Configure AWS OIDC Authentication
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_oidc_role_arn }}
        aws-region: ${{ inputs.aws_region }}

    - name: Action Just
      shell: bash
      run: |
        just ${{ inputs.just_action }}
