on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

concurrency: # only run one instance of workflow at any one time
  group: ${{ github.workflow }}-${{inputs.environment}}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write

jobs:
  oidc:
    environment:
      name: ${{inputs.environment}} # specify environment - seen at /settings/environments/ in UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/terragrunt_action
        with:
          aws_oidc_role_arn: ${{ vars.AWS_OIDC_ROLE_ARN }} # taken from /settings/environments/ 'Environment variables'
          tg_directory: infra/live/${{inputs.environment}}/aws/oidc

  web-infra:
    environment:
      name: ${{inputs.environment}}
    needs: oidc
    runs-on: ubuntu-latest
    outputs:
      bucket_name: ${{ steps.get_vars.outputs.bucket_name }}
      domain: ${{ steps.get_vars.outputs.domain }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy web infrastructure
        uses: ./.github/actions/terragrunt_action
        id: terragrunt_action
        with:
          aws_oidc_role_arn: ${{ vars.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{inputs.environment}}/aws/website
      - name: Get web bucket name
        id: get_vars
        env:
          TG_OUTPUTS: ${{ steps.terragrunt_action.outputs.tg_outputs  }}
        run: |
          echo "bucket_name=$(echo $TG_OUTPUTS | jq -r '.s3_bucket_name.value')" >> $GITHUB_OUTPUT
          echo "domain=$(echo $TG_OUTPUTS | jq -r '.domain.value')" >> $GITHUB_OUTPUT

  web-sync:
    environment:
      name: ${{inputs.environment}}
    needs: web-infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build web files
        uses: ./.github/actions/just_action
        env:
          ASTRO_PUBLIC_BUILD_OWNER: ${{ needs.web-infra.outputs.domain }}
          ASTRO_GITHUB_REPO: ${{ github.action_repository }}
        with:
          aws_oidc_role_arn: ${{ vars.AWS_OIDC_ROLE_ARN }}
          just_action: web-build
      - name: Sync web files to s3
        env:
          BUCKET_NAME: ${{ needs.web-infra.outputs.bucket_name }}
        uses: ./.github/actions/just_action
        with:
          aws_oidc_role_arn: ${{ vars.AWS_OIDC_ROLE_ARN }}
          just_action: web-upload
