name: Kill Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev

concurrency: # only run one instance of workflow at any one time
  group: ${{ github.workflow }}-${{inputs.environment}}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write

env:
  TF_VAR_deploy_version: this

jobs:
  frontend:
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Destroy frontend
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.2.0
        with:
          aws_oidc_role_arn: ${{ vars.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{inputs.environment}}/aws/website
          tg_action: destroy

  backend:
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    needs: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Destroy backend
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.2.0
        with:
          aws_oidc_role_arn: ${{ vars.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{inputs.environment}}/aws/jobs
          tg_action: destroy

  build:
    environment:
      name: ${{ inputs.environment }}
    needs:
      - frontend
      - backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Destroy code
        uses: chrispsheehan/terragrunt-aws-oidc-action@0.2.0
        with:
          aws_oidc_role_arn: ${{ vars.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{inputs.environment}}/aws/code
          tg_action: destroy
