name: Kill Environment

on:
  workflow_dispatch:
    inputs:
      github_environment:
        default: ci
        type: string
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev

concurrency: # only run one instance of workflow at any one time
  group: ${{ github.workflow }}-${{inputs.environment}}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write

env:
  TF_VAR_deploy_version: this

jobs:
  frontend:
    environment:
      name: ${{ inputs.github_environment }}
    runs-on: ubuntu-latest
    env:
      TF_VAR_api_invoke_domain: "does.not.exist"
    steps:
      - uses: actions/checkout@v4

      - name: Destroy frontend
        uses: ./.github/actions/terragrunt_action
        env:
          TF_VAR_api_invoke_domain: no.com
        with:
          aws_oidc_role_arn: ${{ vars.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{inputs.environment}}/aws/website
          tg_action: destroy

  backend:
    environment:
      name: ${{ inputs.github_environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Destroy backend
        uses: ./.github/actions/terragrunt_action
        env:
          TF_VAR_lambda_bucket: bucket
          TF_VAR_lambda_zip: api.zip
          TF_VAR_auth_lambda_zip: auth.zip
        with:
          aws_oidc_role_arn: ${{ vars.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{inputs.environment}}/aws/api
          tg_action: destroy

  security:
    environment:
      name: ${{inputs.environment}}
    needs:
      - frontend
      - backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Destroy security
        uses: ./.github/actions/terragrunt_action
        with:
          aws_oidc_role_arn: ${{ vars.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{inputs.environment}}/aws/security
          tg_action: destroy

  build:
    environment:
      name: ${{ inputs.github_environment }}
    needs:
      - frontend
      - backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Destroy code_bucket
        uses: ./.github/actions/terragrunt_action
        with:
          aws_oidc_role_arn: ${{ vars.AWS_OIDC_ROLE_ARN }}
          tg_directory: infra/live/${{inputs.environment}}/aws/code_bucket
          tg_action: destroy
