name: Check Changes

on:
  workflow_call:
    inputs:
        ref:
            description: 'Git reference to checkout'
            required: false
            default: 'main'
            type: string
    outputs:
        terragrunt:
            description: "Whether terragrunt files changed"
            value: ${{ jobs.changes.outputs.terragrunt == 'true' }}
        github:
            description: "Whether GitHub workflow files changed"
            value: ${{ jobs.changes.outputs.github == 'true' }}
    
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
        terragrunt: ${{ steps.filter.outputs.terragrunt }}
        github: ${{ steps.filter.outputs.github }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            ref: ${{ inputs.ref }}
            fetch-depth: 0

      - name: Detect changed files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            terragrunt:
              - 'infra/**'
            github:
              - '.github/**'
          token: ${{ secrets.GITHUB_TOKEN }}
          list-files: none
          initial-fetch-depth: 100    

      - shell: bash 
        run: echo "terragrunt changes - ${{ steps.filter.outputs.terragrunt }}"

      - shell: bash 
        run: echo "github changes - ${{ steps.filter.outputs.github }}"
