name: Check Changes

on:
  workflow_call:
    inputs:
      ref:
        description: "Git reference to checkout"
        required: false
        default: "main"
        type: string
    outputs:
      terragrunt:
        description: "Whether terragrunt files changed"
        value: ${{ jobs.changes.outputs.terragrunt == 'true' }}
      github:
        description: "Whether GitHub workflow files changed"
        value: ${{ jobs.changes.outputs.github == 'true' }}
      frontend:
        description: "Whether frontend files changed"
        value: ${{ jobs.changes.outputs.frontend == 'true' }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      terragrunt: ${{ steps.filter.outputs.terragrunt }}
      github: ${{ steps.filter.outputs.github }}
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Detect changed files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            terragrunt:
              - 'infra/**'
            github:
              - '.github/**'
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
          token: ${{ secrets.GITHUB_TOKEN }}
          list-files: none
          initial-fetch-depth: 100

      - shell: bash
        run: echo "terragrunt changes - ${{ steps.filter.outputs.terragrunt }}"

      - shell: bash
        run: echo "github changes - ${{ steps.filter.outputs.github }}"

      - shell: bash
        run: echo "frontend changes - ${{ steps.filter.outputs.frontend }}"

      - shell: bash
        run: echo "backend changes - ${{ steps.filter.outputs.backend }}"
