name: Prod deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  prod:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: prod
      version: 0.11.1
