name: Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize, review_requested, ready_for_review]

jobs:
  check:
    uses: ./.github/workflows/get-changes.yml
    with:
      ref: ${{ github.sha }}
