name: Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize, review_requested, ready_for_review]

jobs:
  check:
    permissions:
      pull-requests: read
      contents: read
    uses: ./.github/workflows/get_changes.yml
    with:
      ref: ${{ github.sha }}
    secrets: inherit

  github:
    needs: check
    runs-on: ubuntu-latest
    if: ${{ needs.check.outputs.github == 'true' }}
    name: Run github formatting checks
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: raven-actions/actionlint@v2
        with:
          shellcheck: false
          pyflakes: false

  terragrunt:
    needs: check
    runs-on: ubuntu-latest
    if: ${{ needs.check.outputs.terragrunt == 'true' }}
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - uses: hashicorp/setup-terraform@v3
      - uses: autero1/action-terragrunt@v1.3.2
        with:
          terragrunt_version: 0.45.10

      - name: Terraform fmt check
        run: terraform fmt -check -recursive
        working-directory: infra

      - name: Terragrunt hclfmt check
        run: terragrunt hclfmt --terragrunt-check
        working-directory: infra

  frontend:
    needs: check
    runs-on: ubuntu-latest
    if: ${{ needs.check.outputs.frontend == 'true' }}
    name: Run astro formatting checks
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - name: Run prettier checks
        run: |
          npm install
          npm run format:check
