name: Push on main

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - apigw-refactor

permissions:
  id-token: write
  contents: write

jobs:
  dev:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: dev
