name: Push on main

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      environment: dev
      version: dev

  dev:
    uses: ./.github/workflows/deploy.yml
    needs: build
    secrets: inherit
    with:
      web_bucket: ${{ needs.build.outputs.web_bucket }}
      auth_bucket: ${{ needs.build.outputs.web_bucket }}
      api_bucket: ${{ needs.build.outputs.web_bucket }}
      environment: dev
      version: dev
