name: Push on main

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  oidc:
    environment:
      name: dev # specify environment - seen at /settings/environments/ in UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/terragrunt_action
        with:
          aws_oidc_role_arn: ${{ vars.AWS_OIDC_ROLE_ARN }} # taken from /settings/environments/ 'Environment variables'
          tg_directory: infra/live/ci/aws/oidc

  build:
    needs: oidc
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      environment: dev
      version: ${{ github.sha }}

  dev:
    uses: ./.github/workflows/deploy.yml
    needs: build
    secrets: inherit
    with:
      environment: dev
      version: ${{ github.sha }}
