on:
    workflow_dispatch:
    push:
      branches:
        - main
        - init-gha
    
jobs:
    dev:
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        with:
            environment: dev