name: Push on main

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - reuse-build-yaml

permissions:
  id-token: write
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      environment: dev
      version: ${{github.sha }}

  dev:
    uses: ./.github/workflows/deploy.yml
    needs: build
    secrets: inherit
    with:
      web_bucket: ${{ needs.build.outputs.web_bucket }}
      lambda_bucket: ${{ needs.build.outputs.lambda_bucket }}
      environment: dev
      version: ${{github.sha }}
